<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260729202621_create_company extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
                        name VARCHAR(255) NOT NULL, siret VARCHAR(14) DEFAULT NULL, 
                        description TEXT DEFAULT NULL, 
                        website VARCHAR(255) DEFAULT NULL, 
                        logo VARCHAR(255) DEFAULT NULL, 
                        industry VARCHAR(255) DEFAULT NULL, 
                        zip_code VARCHAR(10) DEFAULT NULL, address VARCHAR(100) DEFAULT NULL, 
                        country VARCHAR(100) DEFAULT NULL, 
                        city VARCHAR(100) DEFAULT NULL, 
                        PRIMARY KEY (id))');
                        
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4FBF094F26E94372 ON company (siret)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, job_titles JSON DEFAULT NULL, locations JSON DEFAULT NULL, contract_types JSON DEFAULT NULL, industry VARCHAR(255) DEFAULT NULL, company_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D649979B1AD6 ON "user" (company_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649979B1AD6');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE "user"');
    }
}
