<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260728001611 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE company ADD industry VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD zip_code VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD address VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD industry VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE user_user');
        $this->addSql('ALTER TABLE company DROP industry');
        $this->addSql('ALTER TABLE company DROP zip_code');
        $this->addSql('ALTER TABLE company DROP address');
        $this->addSql('ALTER TABLE "user" DROP industry');
    }
}
